### ISSUE TITLE
minor UI bugs

### ISSUE THREAD

**Issue by audriusrrr** [audriusrrr/newsfeed#11]
https://basecamp.com/1857203/projects/10534621/todos/205353719

**Comment by driveps** [comment]
" If people clicked something else to leave the page, for them to continue to edit where they left off, users clicking the"sign-up" button should continue where they left off and don't require them to click on "I'm a candidate again" it's pretty annoying and leave some users clueless if they have to go through the extra step. "

In order to fix this issue it would take a lot of time.  Do we wan't to spend time here as it is not as important and wouldn't effect a big audience?
